### ISSUE TITLE
User object

### ISSUE THREAD

**Issue by westwq** [MAD11877/mad21-practical-2---android-activity-DancinComrade#2]
https://github.com/MAD11877/mad21-practical-2---android-activity-DancinComrade/blob/d6d4594e608e0511707800ec35ec3b2cfc85ad29/app/src/main/java/sg/edu/np/mad/practical2/MainActivity.java#L16
initialise it with values and use those values to initialise the textview

**Comment by DancinParrot** [comment]
Issue #2 fixed. Added a parameterised constructer to the User class, and in MainActivity, user object has been initialized with values.

**Comment by DancinComrade** [comment]
Init textviews with values from user object. Pending review.

**Comment by DancinParrot** [comment]
` usernameView.setText(userObj.Name);`

Init textview with values from user object. Pending review, @westwq .
